### ISSUE TITLE
[Milestone] Second template

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-community/templates#28]
Now that there's a first template, there (probably) should come a second. 😉 Preferably another one from https://github.com/microsoft/vscode-dev-containers ? Right now, the forerunners are
- deno #24
- azure py #25 

heres a rough outline

- [x] Define what's worthy of a template
- [x] Create the first template #2 
- [ ] Figure out what the second template should be
- [ ] Write a devcontainer-template.json for it
- [ ] Add a test.sh
- [ ] Document the template in NOTES.md
- [ ] Open a PR to this repo
- [ ] Merge it
- [ ] Publish it

@eitsupi miss anything?

**Comment by jcbhmr** [comment]
> * Define what's worthy of a template

on second thought i think this is done already? right?

![image](https://user-images.githubusercontent.com/61068799/235578430-5d900b9e-78d7-460a-a0de-1c2bce4e1aa9.png)
